### ISSUE TITLE
Axel skal have VPN-adgang til DSL 

### ISSUE THREAD

**Issue by thsh77** [dsldk/salmer_mei#2]
Vi skal i samme anledning se på, hvorfor Axel ikke kan logge på DSL's WPA2 Enterprise-netværk med sin Windows 7-maskine.

**Comment by rj-dsl** [comment]
Er han der på torsdag?

**Comment by axgeertinger** [comment]
Hej René

Jep, jeg er her (dvs. på KB) hele torsdagen. Du kan bare sige til.  Det samme problem [EDIT: altså det med VPN, ikke det trådløse netværk] ]gælder Bjarke Moe. Han er på KB både på torsdag og på mandag (hvor jeg til gengæld ikke er her). For Bjarkes vedkommende gælder det kontormaskinen, så det skulle nok foregå her på kontoret (Diamanten, C-Øst).

/Axel

**Comment by rj-dsl** [comment]
Hej Axel..

Hvor præcist på KB finder jeg jer? Og er I allerede oprettet som brugere i DSLs miljø? Det bliver nok efter kl. 12 jeg kigger over :)

/René

**Comment by axgeertinger** [comment]
Fint! Vi sidder i Diamanten på C-Øst i gangen, der starter lige ved trappen og elevatoren. Jeg sidder i 2. kontor inden for glasdøren. Bare bank på glasdøren, hvis dit kort ikke kan åbne den.
/axel

**Comment by axgeertinger** [comment]
Og ja, både Bjarke og jeg er oprettet i DSL-systemet.
