### ISSUE TITLE
Linje/sideskift vises ikke i mensuralnotation

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#21]
Det har virket tidligere.

**Comment by axgeertinger** [comment]
Ups. Hænger formentlig sammen med løsningen af #18

**Comment by axgeertinger** [comment]
Gælder kun offline-vieweren. Ordnet med commit https://github.com/dsldk/salmer_mei/commit/a45e775ed62c52a7f67f63334e2c3c4b1118140a
