### ISSUE TITLE
Bindebue vises ikke, når kommentar tilføjes om <nc>

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#22]
Se Je_240, linje 490f:
Når der indsættes en kommentar om <nc>, vises slur ikke.

 <syllable xml:id="Je_1573_LN0981_240_m-201_syl">
                           <verse xml:id="Je_1573_LN0981_240_m-201" n="1">
                              <syl xml:id="Je_1573_LN0981_240_m-202" con="d" wordpos="i">vul</syl>
                           </verse>
                           <neume xml:id="neume_d3e487">
                              <reg>
                                 <annot xml:id="Je_1573_LN0981_240_annot2">♭ før ligaturen flyttet til før h</annot>
                                 <nc xml:id="Je_1573_LN0981_240_m-178" oct="3" pname="a" pnum="57" label="dur4"/>
                              <nc xml:id="Je_1573_LN0981_240_m-179" oct="3" pname="b" pnum="58" accid="f"
                                  label="dur4"/>
                              </reg>
                           </neume>
                        </syllable>

**Comment by bmoedsl** [comment]
>  <syllable xml:id="Je_1573_LN0981_240_m-201_syl">
                           <verse xml:id="Je_1573_LN0981_240_m-201" n="1">
                              <syl xml:id="Je_1573_LN0981_240_m-202" con="d" wordpos="i">vul</syl>
                           </verse>
                           <neume xml:id="neume_d3e487">
                              <reg>
                                 <annot xml:id="Je_1573_LN0981_240_annot2">♭ før ligaturen flyttet til før h</annot>
                                 <nc xml:id="Je_1573_LN0981_240_m-178" oct="3" pname="a" pnum="57" label="dur4"/>
                              <nc xml:id="Je_1573_LN0981_240_m-179" oct="3" pname="b" pnum="58" accid="f"
                                  label="dur4"/>
                              </reg>
                           </neume>
                        </syllable>

**Comment by axgeertinger** [comment]
Afventer opdatering af filen på github

**Comment by axgeertinger** [comment]
Commit https://github.com/dsldk/salmer_mei/commit/af1347f8a5b3a801fc75eafa1575f943e494fc97 + https://github.com/dsldk/salmer_mei/commit/d75b11d3ef325d9f2608f1257325028b37875ad0
