### ISSUE TITLE
Sangtekst vises ikke, når kommentar tilføjes om <nc>

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#23]
Se Je_257, linje 2709f

> <syllable xml:id="Je_1573_LN0981_257_m-1084_syl">
                           <verse xml:id="Je_1573_LN0981_257_m-1084" n="1">
                              <syl xml:id="Je_1573_LN0981_257_m-1085" con="d" wordpos="i">di</syl>
                           </verse>
                           <neume xml:id="neume_d3e3156">
                              <reg>
                                 <annot xml:id="Je_1573_LN0981_257_annot2">♭ før forrige node flyttet til før h</annot>
                                 <nc xml:id="Je_1573_LN0981_257_m-1072" oct="3" pname="b" pnum="58" accid="f"
                                  label="dur4"/>
                              </reg>
                           </neume>
                        </syllable>

**Comment by axgeertinger** [comment]
Den version af filen, der ligger github, har ikke annotationen. Afventer en opdatering.

**Comment by axgeertinger** [comment]
Commit https://github.com/dsldk/salmer_mei/commit/af1347f8a5b3a801fc75eafa1575f943e494fc97 + https://github.com/dsldk/salmer_mei/commit/d75b11d3ef325d9f2608f1257325028b37875ad0
