### ISSUE TITLE
<annot> efter <section> skal kun vises ved begyndelsen af system

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#24]
Nu vises kommentaren ved hver ny takt, også i midten af system.

Eks.: Je_3:
Linje 194

>                <section xml:id="Je_1573_LN0981_003_m-32">
                  <annot xml:id="Je_1573_LN0981_003_annot1">dobbeltnøgle: F-nøgle på anden linje og C-nøgle på fjerde linje</annot>
                  <staff xml:id="Je_1573_LN0981_003_m-35" n="1">

**Comment by axgeertinger** [comment]
Ordnet med commit https://github.com/dsldk/salmer_mei/commit/63e9576a09ce4c563568ec71698a4df89691e328
