### ISSUE TITLE
fejl i reduktion af nodeværdier i viewer

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#28]
Longa halveres til helnode (første node i Vo_1539_LN0298_000c02v.xml). Skulle være brevis.

**Comment by axgeertinger** [comment]
Det var noget, vi aftalte i sin tid: Der skulle ikke være nodeværdier større end helnode i reduceret notation, så det er kodet eksplicit som en undtagelse. Men jeg fjerner selvfølgelig gerne undtagelsen, hvis det giver bedre mening.

**Comment by axgeertinger** [comment]
fixed: https://github.com/dsldk/salmer_mei/commit/73bf7f337f2d775344329beaab743ab765aa697b
