### ISSUE TITLE
nummerering af tekstkritiske noter i viewer

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#39]
I følgende fil vises noterne som nummer 10, 2, 3 osv. Senere optræder desuden en note nr. 10 på trods af, at nummereret allerede er brugt. 

Vo_1539_LN0298_000e03v.xml

(pt. lokal fil. Comittes til github snarest)

**Comment by axgeertinger** [comment]
Fixed. https://github.com/dsldk/salmer_mei/commit/ca16f1ab2411ae91045fe02036e9b383dc971c99
