### ISSUE TITLE
rensning af data

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#62]
- blanktegn efter sidste ord i <title> bør fjernes

**Comment by bmoedsl** [comment]
- Jespersøn/Jesperssøn skal rettes til Jespersen

**Comment by axgeertinger** [comment]
Kontroller og ret rækkefølge af elementer: `<classification>` skal komme før `<relationList>`

**Comment by axgeertinger** [comment]
Fjern tomme attributter: level, target, unit, startdate, enddate, notbefore, notafter, isodate, mimetype

**Comment by axgeertinger** [comment]
`<application version="2.1.0 modified for Sibelius 6"><name>SibMEI</name></application>` ændres til `<application version="2.1.0"><name>SibMEI</name> modified for Sibelius 6</application>`
