### ISSUE TITLE
fejl i visning af søgeresultater

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#63]
Søgeresultater i salmebasen vises med fede streger over noderne:

![salmebasen, fejl jan  2020](https://user-images.githubusercontent.com/38459841/73247011-4374d080-41b0-11ea-892f-d7dfd1fcf17a.jpg)

**Comment by axgeertinger** [comment]
Ups - utilsigtet bivirkning af commit https://github.com/dsldk/salmer_mei/commit/c381d14fdaa77c509770c09f28a3f27eda615e73. Ordnet med https://github.com/dsldk/salmer_mei/commit/099198e5456a74805cddda48653686508cd9be9f
