### ISSUE TITLE
nodereduktion i koralnotation

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#68]
fjern mulighed for at reducere nodeværdier i koralnotation. Den specielle værdi, som ligner en fjerdedel, men som blot er en underdeling er hovedværdien, skifter pt. til ottendedele osv. når man reducerer. Værdierne skal blive uforandrede, hvis man prøver at reducere. 

se: https://tekstnet.dk/oluf-ulriksen-messehaandbog-1539/28

**Comment by axgeertinger** [comment]
Fixed: https://github.com/dsldk/salmer_mei/commit/2430669025154707b51f1b3fa26af0cb305f3328. Nodeværdier reduceres ikke på neumer uanset udseende. I satser udelukkende med neumer fjernes muligheden for nodereduktion helt. Den er stadig tilgængelig i blandet notation (fx https://salmer.dsl.dk/document.xq?doc=Th_1569/Th_1569_LN1426_094r.xml)
