### ISSUE TITLE
dansk førstelinje i søgeresultat

### ISSUE THREAD

**Issue by bmoedsl** [dsldk/salmer_mei#71]
Melodiposter viser latinsk alternativ førstelinje i søgninger på salmer.dsl.dk. Se fx: https://salmer.dsl.dk/mei_search.xq?x=&qt=Hvi+storme+og+fnyse+de+hedninger+s%C3%A5

Melodiposten bør vise "Hvi storme og fnyse de hedninger så" i stedet for "Quare fremuerunt gentes".

Så vidt jeg kan regne ud, forekommer den normalisere førstelinje altid i <fileDesc><titleStmt><title>Hvi storme og fnyse de hedninger så</title></titleStmt></fileDesc>

**Comment by axgeertinger** [comment]
Sættes til at bruge første uniforme titel. Alternativt første titel, hvis ingen uniform titel er opgivet. Fikset med https://github.com/dsldk/salmer_mei/commit/792740409a87980b596fc852a9e6a7cf4386c77c + re-indeksering. Sidetitel i document.xq også sat til første uniforme titel.
